version: "3.9"
services:
  app:
    build: .
    container_name: cs2-discord-bot
    env_file: .env
    depends_on:
      - db
    ports:
      - "${HTTP_PORT:-8080}:8080"
    restart: unless-stopped
